# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wishlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 328)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(250, 10, 141, 311))
        self.listWidget.setObjectName("listWidget")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 271))
        self.groupBox.setObjectName("groupBox")
        self.nameEdit = QtWidgets.QTextEdit(self.groupBox)
        self.nameEdit.setGeometry(QtCore.QRect(10, 50, 201, 31))
        self.nameEdit.setObjectName("nameEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.costEdit = QtWidgets.QTextEdit(self.groupBox)
        self.costEdit.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.costEdit.setObjectName("costEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.linkEdit = QtWidgets.QTextEdit(self.groupBox)
        self.linkEdit.setGeometry(QtCore.QRect(10, 170, 201, 31))
        self.linkEdit.setObjectName("linkEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.remarkEdit = QtWidgets.QTextEdit(self.groupBox)
        self.remarkEdit.setGeometry(QtCore.QRect(10, 230, 201, 31))
        self.remarkEdit.setObjectName("remarkEdit")
        self.createButton = QtWidgets.QPushButton(Dialog)
        self.createButton.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.createButton.setObjectName("createButton")
        self.editButton = QtWidgets.QPushButton(Dialog)
        self.editButton.setGeometry(QtCore.QRect(90, 290, 75, 23))
        self.editButton.setObjectName("editButton")
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(170, 290, 75, 23))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wishlist"))
        self.groupBox.setTitle(_translate("Dialog", "Желание"))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Цена"))
        self.label_3.setText(_translate("Dialog", "Ссылка"))
        self.label_4.setText(_translate("Dialog", "Примечание"))
        self.createButton.setText(_translate("Dialog", "Добавить"))
        self.editButton.setText(_translate("Dialog", "Изменить"))
        self.deleteButton.setText(_translate("Dialog", "Удалить"))
